services:
  db:
    image: postgres:16
    container_name: personal_blog_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal_blog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  web:
    build: .
    container_name: personal_blog_web
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/personal_blog
      JWT_SECRET: "dd88a4663489485272ec638830c6a352"
      NEXTAUTH_SECRET: "dd88a4663489485272ec638830c6a352"
      PROFILE_PHOTO_DIR: "/home/ubuntu/profile_photos"
      NEXT_PUBLIC_ENABLE_DIFY: "false"
    ports:
      - "80:3000"
    volumes:
      - /home/ubuntu/profile_photos:/app/public/profile_photos
    networks:
      - app-net

networks:
  app-net:

volumes:
  postgres_data:
